FROM node:24.2.0-alpine AS build-app

ARG VITE_APP_BUILD_VERSION
ENV VITE_APP_BUILD_VERSION=${VITE_APP_BUILD_VERSION}

WORKDIR /app/frontend

COPY ./frontend/package.json .
COPY ./frontend/package-lock.json .

RUN npm install

COPY ./frontend .
COPY .env.prod ../.env.prod

RUN npm run build


FROM nginx:1.28.0-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/production/nginx.conf /etc/nginx

COPY ./nginx/GeoIP.dat /etc/nginx
COPY ./nginx/GeoIPCity.dat /etc/nginx

RUN apk add --no-cache logrotate
COPY ./nginx/logrotate-shareframe /etc/logrotate.d/shareframe
COPY ./nginx/logrotate-cron /etc/periodic/15min/logrotate
COPY ./nginx/start-crond.sh /docker-entrypoint.d/99-start-crond.sh
RUN chmod +x /etc/periodic/15min/logrotate /docker-entrypoint.d/99-start-crond.sh

WORKDIR /usr/share/nginx/html
COPY --from=build-app /app/frontend/build .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]