FROM node:22.3-alpine

ARG VITE_APP_BUILD_VERSION
ENV VITE_APP_BUILD_VERSION=${VITE_APP_BUILD_VERSION}

WORKDIR /app/frontend

COPY package.json .
COPY package-lock.json .
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
