"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
import logging
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", False) == "True"

# 'DJANGO_ALLOWED_HOSTS' should be a single string of hosts with a space between each.
# For example: 'DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]'
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(" ")
CSRF_TRUSTED_ORIGINS = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS").split(" ")
CORS_ALLOWED_ORIGINS = os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS").split(" ")

PRODUCTION = os.environ.get("PRODUCTION", False) == "True"
APP_BUILD_VERSION = os.environ.get("APP_BUILD_VERSION", "")

if PRODUCTION:
    # Trust proxy headers and force HTTPS in production
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
else:
    SECURE_SSL_REDIRECT = False

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.auth",
    "django.contrib.admin",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # THIRDPARTY
    "channels",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "djoser",
    "drf_spectacular",
    "django_celery_results",
    "django_celery_beat",
    "django_otp",
    "django_otp.plugins.otp_totp",
    # APPS
    "frames",
    "frame_updates",
    "authentication",
    "appEmail",
    "user_core",
    "user_accounts",
    "images",
    "friendships",
    "sent_images",
    "changelogs",
    "dashboard",
]

# Upload size limits. App endpoints (/api/...) get a smaller total-request cap
# than the admin (/api/admin/), which needs room for firmware release uploads.
ADMIN_URL_PREFIX = "/api/admin/"
APP_UPLOAD_MAX_SIZE = 25 * 1024 * 1024  # 25 MB
ADMIN_UPLOAD_MAX_SIZE = 100 * 1024 * 1024  # 100 MB

# Must cover the admin ceiling: LoggingMiddleware reads request.body, whose
# Content-Length check (files included) is gated by this setting.
DATA_UPLOAD_MAX_MEMORY_SIZE = ADMIN_UPLOAD_MAX_SIZE
# Memory -> temp-disk threshold only (rejects nothing); keeps RAM low.
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "utils.upload_limits.middleware.UploadSizeLimitMiddleware",
    "utils.request_logging.middleware.LoggingMiddleware",
    "django_otp.middleware.OTPMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Logging
LOGS_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOGS_DIR, exist_ok=True)

LOG_FILES = {
    "default": "backend-default.log",
    "application": "backend-application.log",
    "websockets": "backend-websockets.log",
    "celery": "backend-celery.log",
    "django": "backend-django.log",
    "application-server": "backend-application-server.log",
    "admin-audit": "backend-admin-audit.log",
}

for key, filename in LOG_FILES.items():
    LOG_FILES[key] = os.path.join(LOGS_DIR, filename)

DJANGO_LOG_LEVEL = "DEBUG" if DEBUG else "INFO"

LOGGING_FILE_HANDLER_DEFAULTS = {
    "level": DJANGO_LOG_LEVEL,
    "class": "logging.handlers.RotatingFileHandler",
    "maxBytes": 10 * 1024 * 1024,  # 10 MB
    "backupCount": 2,
    "formatter": "default",
}


# Function to generate file handlers with common configuration
def create_file_handlers(handler_configs=None):
    """
    Create file handlers with default settings that can be overridden.
    """
    handler_configs = handler_configs or {}
    handlers = {}

    for handler_name, log_file in LOG_FILES.items():
        handler_key = f"{handler_name}-file" if handler_name != "default" else "file"

        handler_config = LOGGING_FILE_HANDLER_DEFAULTS.copy()

        handler_config["filename"] = log_file

        if handler_key in handler_configs:
            handler_config.update(handler_configs[handler_key])

        handlers[handler_key] = handler_config

    return handlers


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": "{asctime} [{levelname}] {name} - {funcName} - {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "handlers": {
        "console": {
            "level": DJANGO_LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "default",
        },
        **create_file_handlers(
            {
                # overriding defaults for specific handlers
                "application-file": {
                    "maxBytes": 100 * 1024 * 1024,
                    "backupCount": 3,
                },
                "celery-file": {
                    "maxBytes": 100 * 1024 * 1024,
                    "backupCount": 3,
                },
                "websockets-file": {
                    "maxBytes": 100 * 1024 * 1024,
                    "backupCount": 3,
                },
                "django-file": {
                    "maxBytes": 100 * 1024 * 1024,
                    "backupCount": 3,
                },
            }
        ),  # Add all file handlers with ability to override defaults
    },
    "loggers": {
        # application servers
        "daphne": {
            "handlers": ["application-server-file", "console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "gunicorn": {
            "handlers": ["application-server-file", "console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        # django
        "django": {
            "handlers": ["django-file", "console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "django.server": {
            "handlers": ["django-file", "console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "django.request": {
            "handlers": ["django-file", "console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        # celery
        "celery": {
            "handlers": ["celery-file", "console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "celery.frames": {
            "handlers": ["celery-file", "console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        # websockets
        "websockets": {
            "handlers": ["websockets-file", "console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "websockets.frames": {
            "handlers": ["websockets-file", "console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        # application
        "images": {
            "handlers": ["application-file", "console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        # admin audit
        "admin.audit": {
            "handlers": ["admin-audit-file", "console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
    },
}

REQUEST_LOGGING_DATA_LOG_LEVEL = getattr(
    logging, DJANGO_LOG_LEVEL.upper(), logging.INFO
)
DJANGO_REQUEST_LOGGING_LOG_BODY_DEFAULT_VALUE = True
DJANGO_REQUEST_LOGGING_LOG_RESPONSE_DEFAULT_VALUE = False
REQUEST_LOGGING_ENABLE_COLORIZE = False

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("DB_NAME", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("DB_USER", "user"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "password"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f'redis://{os.environ.get("REDIS_HOST", "redis")}:{os.environ.get("REDIS_PORT", "6379")}/{os.environ.get("REDIS_DB", "0")}',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Berlin"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/api/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/api/media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "user_core.User"

AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_METADATA_CLASS": "rest_framework.metadata.SimpleMetadata",
    # "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    # "PAGE_SIZE": 25,
    "DEFAULT_THROTTLE_CLASSES": [
        "config.throttles.BurstRateThrottle",
        "config.throttles.SustainedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "burst": "60/min",
        "sustained": "1000/day",
        # images
        "images_burst": "3000/min",
        "images_sustained": "10000/day",
        # media views
        "media_burst": "3000/min",
        "media_sustained": "10000/day",
        "frame_updates_burst": "20/min",
        "frame_updates_sustained": "100/day",
        "changelogs_burst": "1000/min",
        "changelogs_sustained": "3000/day",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    # Cryptographic settings
    "ALGORITHM": "HS256",
    "SIGNING_KEY": os.environ.get("SECRET_KEY"),
    "VERIFYING_KEY": None,
    # Token customization
    "AUDIENCE": "shareframe-api",
    "ISSUER": "shareframe-api",
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    # User identification
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
}

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.MD5PasswordHasher",
]

DJOSER = {
    "LOGIN_FIELD": "email",
    "USER_ID_FIELD": "id",
    "USER_CREATE_PASSWORD_RETYPE": True,
    "SET_PASSWORD_RETYPE": True,
    "PASSWORD_RESET_CONFIRM_RETYPE": True,
    "SEND_ACTIVATION_EMAIL": True,
    "SEND_CONFIRMATION_EMAIL": True,
    "USERNAME_CHANGED_EMAIL_CONFIRMATION": False,
    "PASSWORD_CHANGED_EMAIL_CONFIRMATION": True,
    "HIDE_USERS": True,
    # FRONTEND_URLS
    # "USERNAME_RESET_CONFIRM_URL": "auth/users/email-reset/{uid}/{token}",
    "PASSWORD_RESET_CONFIRM_URL": "auth/users/password-reset/{uid}/{token}",
    "ACTIVATION_URL": "auth/users/activate/{uid}/{token}",
    "SERIALIZERS": {
        "user_create": "user_core.serializers.UserCreateSerializer",
        "user": "user_core.serializers.UserRetrievePatchSerializer",
        "current_user": "user_core.serializers.UserRetrievePatchSerializer",
        "user_delete": "user_core.serializers.UserRetrieveSerializer",
    },
    "EMAIL": {
        "activation": "appEmail.djoserEmailConfig.DjoserActivationEmail",
        "confirmation": "appEmail.djoserEmailConfig.DjoserConfirmationEmail",
        "password_reset": "appEmail.djoserEmailConfig.DjoserPasswordResetEmail",
        "password_changed_confirmation": "appEmail.djoserEmailConfig.DjoserPasswordChangedConfirmationEmail",
    },
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "address": f'redis://{os.environ.get("REDIS_HOST", "redis")}:{os.environ.get("REDIS_PORT", "6379")}/{os.environ.get("REDIS_DB", "0")}',
                }
            ]
        },
    }
}

SPECTACULAR_SETTINGS = {
    "TITLE": "ShareFrame API",
    "DESCRIPTION": "Endpoints and possible interactions with the API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

if PRODUCTION:
    EMAIL_HOST = os.environ.get("EMAIL_HOST")
    EMAIL_PORT = os.environ.get("EMAIL_PORT", default=587)
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    DEFAULT_FROM_EMAIL = os.environ.get("EMAIL_HOST_USER")
else:
    EMAIL_HOST = os.environ.get("EMAIL_HOST", "mailhog")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 1025))
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_TLS = False
    EMAIL_USE_SSL = False
    DEFAULT_FROM_EMAIL = os.environ.get("EMAIL_HOST_USER", "dev@shareframe.local")

# Recipient for admin login / failed-login notifications.
# Falls back to DEFAULT_FROM_EMAIL when unset.
ADMIN_NOTIFICATION_EMAIL = os.environ.get("ADMIN_NOTIFICATION_EMAIL", DEFAULT_FROM_EMAIL)

#### Images
IMAGES_ALLOWED_FORMATS = ["jpg", "png", "jpeg"]
IMAGES_MAX_FILE_SIZE = 20 * 1024 * 1024  # 20 MB
IMAGES_MAX_IMAGES_NUMBER = int(
    os.environ.get("DJANGO_IMAGES_UPLOADED_FILES_MAX_FILES_TOTAL", 100)
)
IMAGES_AUTO_DELETE_INTERVAL_HOURS = float(
    os.environ.get("DJANGO_IMAGES_AUTO_DELETE_INTERVAL_HOURS", 3)
)

#### Frames
FRAME_SENT_IMAGE_COOLDOWN_PERIOD_SECONDS = 300  # seconds
FRAME_AUTH_SECRET_KEY = os.environ.get("DJANGO_FRAME_AUTH_SECRET_KEY")
FRAME_AUTH_TIMESTAMP_VALIDATION_WINDOW_MIN = 15
FRAME_HEARTBEAT_TIMEOUT_MINUTES = 60

#### Frontend URLS
FRONTEND_CONTACT_URL = "kontakt/"

#### Sent_Images
# Number of days after expiration before deleting sent images
SENT_IMAGE_DELETE_DAYS = 14  # days
