services:
  backend: &backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/app/backend
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      backend_db:
        condition: service_healthy
      redis:
        condition: service_started

  websockets:
    container_name: websockets
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    command: daphne --proxy-headers -b 0.0.0.0 -p 9000 config.asgi:application
    entrypoint: []
    volumes:
      - ./backend/:/app/backend
    ports:
      - 9000:9000
    env_file:
      - ./.env.dev
    depends_on:
      backend_db:
        condition: service_healthy
      redis:
        condition: service_healthy

  backend_db:
    container_name: backend_db
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
      - backend_db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_data:/data

  celery:
    container_name: celery
    <<: *backend
    command: celery -A config worker --loglevel=info -n worker1
    depends_on:
      - redis
    entrypoint: []
    ports: []

  celery-beat:
    container_name: celery-beat
    <<: *backend
    command: celery -A config beat
    depends_on:
      - redis
    entrypoint: []
    ports: []

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        VITE_APP_BUILD_VERSION: ${VITE_APP_BUILD_VERSION}
    volumes:
      - ./frontend:/app/frontend
      - node_modules:/app/frontend/node_modules
    env_file:
      - ./.env.dev
    ports:
      - "3000:3000"

volumes:
  backend_db_data:
  node_modules: {}
  redis_data:
