services:
  backend: &backend
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --log-level info --access-logfile /home/app/backend/logs/backend-application-server.log --error-logfile /home/app/backend/logs/backend-application-server.log
    volumes:
      - static_volume:/home/app/backend/staticfiles
      - media_volume:/home/app/backend/mediafiles
      - logs_volume:/home/app/backend/logs
    expose:
      - 8000
    env_file:
      - ./.env.prod.local
    depends_on:
      backend_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend_network
      - backend_db_network
      - redis_network

  websockets:
    container_name: websockets
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile.prod
    command: daphne --proxy-headers -b 0.0.0.0 -p 9000 -v 3 config.asgi:application --access-log /home/app/backend/logs/backend-application-server.log
    entrypoint: []
    volumes:
      - media_volume:/home/app/backend/mediafiles
      - logs_volume:/home/app/backend/logs
    expose:
      - 9000
    env_file:
      - ./.env.prod.local
    depends_on:
      backend_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend_network
      - backend_db_network
      - redis_network

  backend_db:
    container_name: backend_db
    image: postgres:15
    restart: always
    env_file:
      - ./.env.prod.local
    volumes:
      - backend_db_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_db_network

  redis:
    container_name: redis
    image: redis:6.2-alpine
    command: redis-server --appendonly yes --appendfsync everysec --save 60 1 --loglevel notice
    expose:
      - 6379
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - redis_network

  celery:
    <<: *backend
    container_name: celery
    restart: always
    command: celery -A config worker --loglevel=info -n worker1
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    entrypoint: []
    ports: []
    networks:
      - backend_network
      - redis_network

  celery-beat:
    <<: *backend
    container_name: celery-beat
    restart: always
    command: celery -A config beat --loglevel=INFO
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    entrypoint: []
    ports: []
    networks:
      - backend_network
      - redis_network

  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.prod.local
      args:
        VITE_APP_BUILD_VERSION: ${VITE_APP_BUILD_VERSION}
    volumes:
      - static_volume:/home/app/backend/staticfiles
      - media_volume:/home/app/backend/mediafiles
      - logs_volume:/home/app/backend/logs
    depends_on:
      backend:
        condition: service_started
      websockets:
        condition: service_started
    ports:
      - 80:80
    env_file:
      - ./.env.prod.local
    networks:
      - frontend_network
      - backend_network

volumes:
  backend_db_data:
  static_volume:
  media_volume:
  logs_volume:
  redis_data:


networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
  backend_db_network:
    driver: bridge
  redis_network:
    driver: bridge
