# Generated by Django 5.1.4 on 2025-05-17 17:06

import changelogs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=changelogs.models.changelog_image_upload_path)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('changelog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='changelogs.changelog')),
            ],
        ),
    ]
