# Generated by Django 5.1.4 on 2025-05-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelogs', '0002_changelogimage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='changelogimage',
            constraint=models.UniqueConstraint(fields=('changelog', 'tag'), name='unique_tag_per_changelog'),
        ),
    ]
