# Generated by Django 5.1.4 on 2025-06-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelogs', '0003_changelogimage_unique_tag_per_changelog'),
        ('frames', '0008_framegroup_frame_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='changelogs', to='frames.framegroup'),
        ),
    ]
