# Generated by Django 6.0.8 on 2026-10-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelogs', '0004_changelog_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
