# Generated by Django 5.1.4 on 2025-02-21 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Version must be in semantic versioning format (e.g., 1.0.0)', regex='^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$')])),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('download_url', models.URLField(max_length=500)),
                ('checksum', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('release_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
