# Generated by Django 5.1.4 on 2025-03-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame_updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='criticality',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Important', 'Important'), ('Minor', 'Minor'), ('Patch', 'Patch')], default='Patch', max_length=10),
        ),
    ]
