# Generated by Django 5.1.4 on 2025-05-23 18:08

import frame_updates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame_updates', '0002_release_criticality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='download_url',
        ),
        migrations.AddField(
            model_name='release',
            name='file',
            field=models.FileField(null=True, upload_to=frame_updates.models.release_file_upload_path),
        ),
    ]
