# Generated by Django 5.1.4 on 2025-05-23 19:40

import frame_updates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame_updates', '0003_remove_release_download_url_release_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='file',
            field=models.FileField(upload_to=frame_updates.models.release_file_upload_path),
        ),
    ]
