# Generated by Django 5.1.4 on 2025-06-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame_updates', '0004_alter_release_file'),
        ('frames', '0008_framegroup_frame_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='releases', to='frames.framegroup'),
        ),
    ]
