# Generated by Django 5.1.4 on 2025-02-27 21:11

import django.db.models.deletion
import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('quality', models.PositiveIntegerField(default=85)),
            ],
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='image',
            name='format',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=images.models.get_original_upload_path),
        ),
        migrations.CreateModel(
            name='ImageVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=images.models.get_variant_upload_path)),
                ('image_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.imagesize')),
                ('parent_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='images.image')),
            ],
            options={
                'unique_together': {('image_size', 'parent_image')},
            },
        ),
    ]
