# Generated by Django 5.1.4 on 2025-04-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_imagesize_alter_image_options_image_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='display_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='image',
            name='markedAsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
