# Generated by Django 5.1.4 on 2025-07-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_display_name_image_markedasdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='auto_delete_after_period',
            field=models.BooleanField(default=False),
        ),
    ]
