# Generated by Django 5.1.4 on 2024-12-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frametoken',
            name='last_obtained',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
