# Generated by Django 5.1.4 on 2025-03-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0002_frametoken_last_obtained'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='framewebsocketconnection',
            name='local_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
