# Generated by Django 5.1.4 on 2025-03-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0003_frame_last_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='version',
            field=models.CharField(default='1.0.0', max_length=100),
        ),
    ]
