# Generated by Django 5.1.4 on 2025-03-17 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0004_frame_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('frame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frame_otp', to='frames.frame')),
            ],
        ),
    ]
