# Generated by Django 5.1.4 on 2025-03-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0005_frameotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framewebsocketconnection',
            name='local_ip_address',
        ),
        migrations.AddField(
            model_name='frame',
            name='local_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
