# Generated by Django 5.1.4 on 2025-03-29 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0006_remove_framewebsocketconnection_local_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='last_board_heartbeat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
