# Generated by Django 5.1.4 on 2025-06-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0007_frame_last_board_heartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='frames', to='frames.framegroup'),
        ),
    ]
