# Generated by Django 5.1.4 on 2026-06-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0009_consolidate_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='public_key',
            field=models.CharField(blank=True, help_text='Base64-encoded ed25519 public key (32 bytes).', max_length=44, null=True, unique=True),
        ),
    ]
