# Generated by Django 5.1.4 on 2024-12-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0002_alter_friendship_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set(),
        ),
    ]
