# Generated by Django 5.1.4 on 2024-12-10 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_core', '0003_user_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('friendship_user_searchable', models.BooleanField(default=True)),
                ('friendship_user_search_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
