# Generated by Django 5.1.4 on 2024-12-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0003_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
